### ISSUE TITLE
Not working in ios 13.

### ISSUE THREAD

**Issue by OttoChamo** [saitbnzl/flutter_paycards#4]
I am working on a project that involves reading credit cards from the camera, I installed your package and I have an Iphone XR when I run the app on it, the ViewController for the camera appears but It doesn't read the cards, nothing happens :c

**Comment by saitbnzl** [comment]
@OttoChamo I have published version 0.2.0 that fixes this issue.

Additionally, you use startRecognizer() as a method now. You can also provide a bool value to open the view as fullScreen in IOS 13:

`startRecognizer(fullScreen: true);`

**Comment by OttoChamo** [comment]
@saitbnzl Thank you very much my friend. You saved me :)

**Comment by saitbnzl** [comment]
@OttoChamo You're welcome :) I want to improve this package until developers of PayCards decides to develop an official package. Because the SDK is very successful in my experience. So, feel free to make recommendations when you have any.
