### ISSUE TITLE
Back button says "Iptal"

### ISSUE THREAD

**Issue by EirikFladby** [saitbnzl/flutter_paycards#8]
Hi, the back button on iOS says "Iptal". Any way to change this?

**Comment by OlehKhalamyrenko** [comment]
Hi, I think it's rather a "Cancel" button. Could you please fix it?

**Comment by saitbnzl** [comment]
Hi. Sorry for my too late response :) I've fixed it with the latest commits. Now it's set to "Cancel" by default. Also, you can change it with **cancelLabel** parameter. Like:

`await FlutterPaycards.startRecognizer(cancelLabel: 'Cancel');`

I can't publish it to pub right now. You will need to use it from GitHub.

**Comment by saitbnzl** [comment]
It's published on pub now. (0.2.4)
